### ISSUE TITLE
Explorer: Firespray + Curved Tie combination cannot be selected

### ISSUE THREAD

**Issue by Lenni009** [blackholesuns/nmsce#11]
The Firespray Explorer body cannot be selected together with the Curved Tie wings, although one of them has been found by Spiper.
https://www.reddit.com/r/NMSCoordinateExchange/comments/p2mjr8/in_almost_10000_ships_ive_logged_this_is_the_only/

![Screenshot](https://firebasestorage.googleapis.com/v0/b/nms-bhs.appspot.com/o/nmsce%2Fdisp%2F702ba2b8-e014-474b-8dfa-7d9034f3078e.jpg?alt=media&token=5a40391b-b25f-4d6f-b60f-b49920d20cd1)

**Comment by CEbbinghaus** [comment]
Verified in Production. Needs to be fixed. Thank you so much 👍🏼

**Comment by CEbbinghaus** [comment]
After some more research, this is in fact not an issue since the combination is in fact invalid. This ship should have never existed and dissapeared with the exploration update so the Reddit post is incorrect.

**Comment by Lenni009** [comment]
Ah, thanks for clarifying 👍
