### ISSUE TITLE
Glyphreader not working

### ISSUE THREAD

**Issue by Lenni009** [blackholesuns/nmsce#15]
The glyph reader function on the [nmsce](https://nmsce.com/glyph) page is not working correctly.

I click the upload button and selected an image which clearly has glyphs on a quite uniform background. The webapp doesn't show any glyphs tho.

I tested this in Google Chrome v102 and Firefox v101, both did not work. Here's a screenshot of how it looked after uploading the picture:
![GlyphNotWorking](https://user-images.githubusercontent.com/91371655/174114996-c13dbe58-76e3-4c93-9e7e-2d0a072ca653.png)

This was the picture that was uploaded:
![20220213122518_1](https://user-images.githubusercontent.com/91371655/174115084-a0acca8f-f8e2-44fe-b4f2-b712ab1b4dd0.jpg)

**Comment by CEbbinghaus** [comment]
Confirmed Issue. Thank's for pointing that out. Will be fixed in the next update

**Comment by Lenni009** [comment]
This still doesn't work. I have hard-reloaded the page, meaning it can't be a caching issue on my side.
Why was this issue closed?
