### ISSUE TITLE
Search Not Working (The site doesn't seem to be either)

### ISSUE THREAD

**Issue by LeJayKay** [blackholesuns/nmsce#23]
As of a couple days ago, the coordinate search button hasn't been working. I had this problem when the site was new as well. I'm able to fill in all the information fields, but "search" is a dead button. I'm on an updated mobile device. (Edit: most page tabs show up blank as well. And quite a bit of the website acts like the search bar problem)

**Comment by CEbbinghaus** [comment]
can you confirm the URL you are accessing and the device/browser you are using?
